language: php
install:
  - pear upgrade pear
  - pear install package.xml
  - wget https://phar.phpunit.de/phpunit-5.7.phar
  - phpenv rehash
php:
  - 5.6
  - 7.0
  - 7.1
sudo: false
script: php phpunit-5.7.phar tests/
